# -*- coding: utf-8 -*-
"""story generater.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TcN3FuWOpwd-SOlrF5jy0msNncsJ6NSO
"""

import random
import string

def generate_story():
  """Generates a random story."""
  characters = ["John", "Mary", "Peter", "Susan", "Jane", "Bill"]
  verbs = ["walked", "ran", "jumped", "skipped", "danced", "swam"]
  nouns = ["dog", "cat", "ball", "tree", "house", "car"]

  story = ""
  for i in range(10):
    character = random.choice(characters)
    verb = random.choice(verbs)
    noun = random.choice(nouns)
    story += f"{character} {verb} the {noun}.\n"

  return story

if __name__ == "__main__":
  story = generate_story()
  print(story)

